name: Track Dependencies
on: 
  workflow_dispatch: {}
jobs:
  trackDependencies:
    name: Track Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library
          restore-keys: Library-
      - name: Track Dependencies
        uses: game-ci/track-dependencies@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: 'upm'
          output-file: 'dependencies.json'
      - name: Upload Dependencies
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: dependencies.json